### ISSUE TITLE
Issue 1- Create React app and convert existing HTML 

### ISSUE THREAD

**Issue by hannahhoanggg** [hannahhoanggg/code-journal-react#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Create a responsive form that allows users to store an image URL with some notes about a specific topic.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user opens up the web browser, the website will display an entry form. 

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the React App.
- [x] Add initial components and render the content to the page.
- [x] Create the data.js file and save JavaScript file to local storage.
- [x] Convert the HTML and CSS to the new components .
- [x] Figure out the props that are needed and decide which components will need "useState".
- [] Test to see if functionality allows user to swap between views and if data model is working.
- [x] Add buttons to differentiate component between create and edit page. 
- [] Test all functionality.
- [] Remove unnecessary CSS.
- [] Fix all the errors.
